services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - WATCHPACK_POLLING=true
    volumes:
      - .:/app
      - /app/node_modules
    command: pnpm dev
    restart: unless-stopped
